### ISSUE TITLE
제출 파일 관련 질문입니다

### ISSUE THREAD

**Issue by zsooflow** [snuwebprogramming/code-crush-saga#4]
교수님 안녕하세요..! 벤창웹 수강하고 있는 김지수입니다.
제출 파일 형식 관련 질문이 있습니다.

1. 제출 파일 안에는 html, css, js 파일만 들어가면 되는 거 맞을까요?

2. 제가 추가 구현 1,2까지 구현하고 제출을 했는데, 혹시 추가 구현시 따로 표기해야 하는 사항이 있을까요? 3은 따로 구현하지 않아서요..! 감사합니다 :)

**Comment by zsooflow** [comment]
그리고 혹시 감점 요인에
"새로 생성된 블럭에서 3-match가 일어나지 않음" 이게 있는데,
저는 이 말을 "새로 생성된 블럭에서 3-match가 있는데도 안 일어남" 으로 해석했습니다만,
혹시 "새로 생성된 블럭에서 3-match가 일어나지 않는(=game over)" 경우를 말씀하시는 건가요..?

**Comment by zsooflow** [comment]
+ 더하여, 추가 구현 2를 구현할 때 처음 initBoard에서 3match가 일어난 부분들을 다 제거하고 시작하게끔 하긴 했는데, handle3Match에서 time out이 설정되어 있다보니 이게 적용되는 게 눈에 보이긴 하네요..

물론 처음의 points는 제가 따로 블록을 움직이지 않는 이상 0이 되도록 설정했습니다.

지금 상황은 처음에 3match가 일어나서 없어지는 게 보이지만 points는 항상 0인 상황인데, 혹시 3match가 일어나는게 아예 처음에 안 보이시길 원하는 걸까요??

**Comment by realcom** [comment]
> 교수님 안녕하세요..! 벤창웹 수강하고 있는 김지수입니다.
> 제출 파일 형식 관련 질문이 있습니다.
> 
> 1. 제출 파일 안에는 html, css, js 파일만 들어가면 되는 거 맞을까요?

네
> 2. 제가 추가 구현 1,2까지 구현하고 제출을 했는데, 혹시 추가 구현시 따로 표기해야 하는 사항이 있을까요? 3은 따로 구현하지 않아서요..! 감사합니다 :)

아니오.

**Comment by realcom** [comment]
> 그리고 혹시 감점 요인에
> "새로 생성된 블럭에서 3-match가 일어나지 않음" 이게 있는데,
> 저는 이 말을 "새로 생성된 블럭에서 3-match가 있는데도 안 일어남" 으로 해석했습니다만,
> 혹시 "새로 생성된 블럭에서 3-match가 일어나지 않는(=game over)" 경우를 말씀하시는 건가요..?

"새로 생성된 블럭에서 3-match가 있는데도 안 일어남" 이 맞습니다.

**Comment by realcom** [comment]
> * 더하여, 추가 구현 2를 구현할 때 처음 initBoard에서 3match가 일어난 부분들을 다 제거하고 시작하게끔 하긴 했는데, handle3Match에서 time out이 설정되어 있다보니 이게 적용되는 게 눈에 보이긴 하네요..
> 
> 물론 처음의 points는 제가 따로 블록을 움직이지 않는 이상 0이 되도록 설정했습니다.
> 
> 지금 상황은 처음에 3match가 일어나서 없어지는 게 보이지만 points는 항상 0인 상황인데, 혹시 3match가 일어나는게 아예 처음에 안 보이시길 원하는 걸까요??

파라미티를 하나 넘겨서, 처음 실행할 때는 timeout=0으로 실행 할수 있도록 하면 될 것 같습니다.

**Comment by zsooflow** [comment]
> > * 더하여, 추가 구현 2를 구현할 때 처음 initBoard에서 3match가 일어난 부분들을 다 제거하고 시작하게끔 하긴 했는데, handle3Match에서 time out이 설정되어 있다보니 이게 적용되는 게 눈에 보이긴 하네요..
> > 
> > 물론 처음의 points는 제가 따로 블록을 움직이지 않는 이상 0이 되도록 설정했습니다.
> > 지금 상황은 처음에 3match가 일어나서 없어지는 게 보이지만 points는 항상 0인 상황인데, 혹시 3match가 일어나는게 아예 처음에 안 보이시길 원하는 걸까요??
> 
> 파라미티를 하나 넘겨서, 처음 실행할 때는 timeout=0으로 실행 할수 있도록 하면 될 것 같습니다.

이렇게 수정해서 다시 제출했습니다 :)
답변 감사드립니다~~ 즐거운 저녁 시간 보내세요!
